### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by web75018** [fliverdev/driver#14]
Hi guys.
Can't fixe this error:

1/ flutter clean
2/ flutter pub get
3/ flutter run
Then: 
<img width="1280" alt="Screen Shot 2020-03-06 at 2 51 45 PM" src="https://user-images.githubusercontent.com/7768424/76089483-08896800-5fba-11ea-8a52-47cc8afccd9a.png">
=> 'UserAgent.h' file not found

even if:
cd ios
pod update Firebase/Firestore
rm -rf Pods

Any suggestion? thanks.

**Comment by urmilshroff** [comment]
Have you replaced the existing `AppDelegate.swift` file with your own, and added your own API key to it? Take a look at the instructions in [ENCRYPTION.md](https://github.com/fliverdev/driver/blob/master/ENCRYPTION.md).
